replicaCount: 1

namespace: development

deployment:
  labels:
    environment: development

image:
  tag: "1.0"
  pullPolicy: Always

env:
  FORMULA_PARSER_DEBUG: "true"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "250m"

variables:
  secrets: development-secret
  config: development-config
