version: 2
updates:
    - package-ecosystem: npm
      schedule:
          interval: weekly
      directory: /
      allow:
          - dependency-type: direct
      groups:
          dependencies:
              patterns:
                  - "*"

    - package-ecosystem: uv
      schedule:
          interval: weekly
      directories:
          - /apps/backend/api
          - /apps/backend/parsers/ddl-generator
          - /apps/backend/parsers/excel-reader
          - /apps/backend/parsers/sql-builder
          - /apps/backend/typechecking
          - /apps/connections/database
          - /packages/autoscaler
          - /packages/messaging-utils/messaging-utils-py
          - /packages/proto-utils/proto-utils-py
          - /tools/benchmarks
      allow:
          - dependency-type: direct
      groups:
          dependencies:
              patterns:
                  - "*"
