replicaCount: 1

namespace: development

deployment:
  labels:
    environment: development

image:
  tag: "1.0"
  pullPolicy: Always

env:
  EXCEL_READER_DEBUG: "true"

resources:
  requests:
    memory: "512Mi"
    cpu: "200m"
  limits:
    memory: "1Gi"
    cpu: "500m"

variables:
  secrets: development-secret
  config: development-config
