replicaCount: 1

namespace: development

deployment:
  labels:
    environment: development

image:
  tag: "1.0"
  pullPolicy: Always

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

env:
  DATABASE_CONNECTION_DEBUG: "true"

variables:
  secrets: development-secret
  config: development-config
