# Default values
replicaCount: 1

image:
  repository: dosquisd/etl-database
  tag: "1.0"
  pullPolicy: Always

namespace: development

deployment:
  name: etl-database
  labels:
    app: etl-database
    component: etl-database
    environment: development

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

port:
  containerPort: 50050
  name: grpc

service:
  internal:
    name: etl-database
    type: ClusterIP
    port: 50050

# Dependency services
dependencies:
  redis:
    host: redis
    port: 6379
  mongo:
    host: mongo
    port: 27017

# Environment variables
env:
  DATABASE_CONNECTION_HOST: "0.0.0.0"
  DATABASE_CONNECTION_PORT: "50050"
  DATABASE_CONNECTION_DEBUG: "false"

variables:
  secrets: development-secret
  config: development-config
