apiVersion: v2
name: etl-ddl-generator
description: a gRPC service that converts Excel formula Abstract Syntax Trees (AST) into SQL expressions. This service is responsible for translating the hierarchical structure of Excel formulas into equivalent SQL statements that can be used in database queries.
type: application
version: 1.0.0 # Version of the chart
appVersion: "1.0" # Version of the application

maintainers:
  - name: Juan Perez
  - name: Mauro Gonzalez
  - name: Diederik Monta√±o
