apiVersion: v2
name: etl-database
description: A gRPC service that manages database connections and schema versions for various databases (MongoDB and Redis). This service handles the storage, retrieval, and versioning of database schemas, ensuring that applications can interact with databases using the correct schema definitions.
type: application
version: 1.0.0 # Version of the chart
appVersion: "1.0" # Version of the application

maintainers:
  - name: Juan Perez
  - name: Mauro Gonzalez
  - name: Diederik Monta√±o
