apiVersion: v1
kind: Service
metadata:
  name: etl-api
  namespace: development
  labels:
    app: etl-api
    component: etl-api
    environment: development
spec:
  type: ClusterIP
  selector:
    app: etl-api
    component: etl-api
    environment: development
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: etl-api-external
  namespace: development
  labels:
    app: etl-api
    component: etl-api
    environment: development
spec:
  type: LoadBalancer
  selector:
    app: etl-api
    component: etl-api
    environment: development
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
