apiVersion: v1
kind: Service
metadata:
  name: etl-database
  namespace: development
  labels:
    app: etl-database
    component: etl-database
    environment: development
spec:
  type: ClusterIP
  selector:
    app: etl-database
    component: etl-database
    environment: development
  ports:
    - name: grpc
      port: 50050
      targetPort: 50050
      protocol: TCP
