apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: development
  labels:
    app: mongo
    component: mongo
    environment: development
spec:
  type: ClusterIP
  selector:
    app: mongo
    component: mongo
    environment: development
  ports:
    - port: 27017
      targetPort: 27017
