apiVersion: v1
kind: Service
metadata:
  name: rabbit-amqp
  namespace: development
  labels:
    app: rabbit
    component: rabbit
    environment: development
spec:
  type: ClusterIP
  selector:
    app: rabbit
    component: rabbit
    environment: development
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-management
  namespace: development
  labels:
    app: rabbit
    component: rabbit
    environment: development
spec:
  type: LoadBalancer
  selector:
    app: rabbit
    component: rabbit
    environment: development
  ports:
    - name: management
      port: 15672
      targetPort: 15672
      protocol: TCP
