apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.internal.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.deployment.labels | nindent 4 }}
spec:
  type: {{ .Values.service.internal.type }}
  selector:
    app: {{ .Values.deployment.labels.app }}
    component: {{ .Values.deployment.labels.component }}
    environment: {{ .Values.deployment.labels.environment }}
  ports:
    - name: http
      port: {{ .Values.service.internal.port }}
      targetPort: {{ .Values.port.containerPort }}
      protocol: TCP
