[project]
name = "messaging-utils"
version = "0.1.0"
description = "Utilities for publishing messages to a messaging system."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "proto-utils",
    "pika>=1.3.2",
    "aio-pika>=9.5.7",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "pytest-sugar>=1.1.1",
    "pytest-xdist>=3.8.0",
    "ruff>=0.13.0",
]

[tool.uv.sources]
proto-utils = { path = "../../proto-utils/proto-utils-py", editable = true }

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["messaging_utils*"]

[tool.ruff]
line-length = 80
target-version = "py312"
lint.extend-select = ["I"]
