# envsubst < k8s/development/secrets.yaml | kubectl apply -f - --namespace development

apiVersion: v1
kind: Secret
metadata:
  name: development-secret
  namespace: development
  labels:
    app: etl-design
    component: secrets
    environment: development
type: Opaque
stringData:
  REDIS_HOST: ${REDIS_HOST}
  REDIS_PASSWORD: ${REDIS_PASSWORD}

  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  MONGO_HOST: ${MONGO_HOST}
  MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  RABBITMQ_HOST: ${RABBITMQ_HOST}
  RABBITMQ_USER: ${RABBITMQ_USER}
  RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

  # API Service related
  CORS_ORIGINS: "${CORS_ORIGINS}"
  SECRET_KEY: ${SECRET_KEY}
  FIRST_SUPERUSER: ${FIRST_SUPERUSER}
  FIRST_SUPERUSER_PASSWORD: ${FIRST_SUPERUSER_PASSWORD}
