apiVersion: v2
name: etl-ddl-generator
description: a service that serves as the main entry point for the Excel Parsing system. This service processes Excel files, extracts formulas and data, and orchestrates communication with other microservices to generate SQL statements.
type: application
version: 1.0.0 # Version of the chart
appVersion: "1.0" # Version of the application

maintainers:
  - name: Juan Perez
  - name: Mauro Gonzalez
  - name: Diederik Monta√±o
