replicaCount: 2

namespace: staging

deployment:
  labels:
    environment: staging

image:
  tag: "1.0"
  pullPolicy: IfNotPresent

env:
  EXCEL_READER_DEBUG: "false"

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1000m"

variables:
  secrets: staging-secret
  config: staging-config
