replicaCount: 4

namespace: production

deployment:
  labels:
    environment: production

image:
  tag: "1.0"
  pullPolicy: IfNotPresent

env:
  EXCEL_READER_DEBUG: "false"

resources:
  requests:
    memory: "2Gi"
    cpu: "1000m"
  limits:
    memory: "4Gi"
    cpu: "2000m"

variables:
  secrets: production-secret
  config: production-config
