apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: typechecking-mongo-pvc
  namespace: development
  labels:
    app: mongo
    component: mongo
    environment: development
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
