apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: typechecking-rabbit-data
  namespace: development
  labels:
    app: rabbit
    component: rabbit
    environment: development
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "2Gi"
