apiVersion: v2
name: etl-api
description: API layer to communicate with backend services
type: application
version: 1.0.0 # Version of the chart
appVersion: "1.0" # Version of the application

maintainers:
  - name: Juan Perez
  - name: Mauro Gonzalez
  - name: Diederik Monta√±o
