name: Reusable CI Tests

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      env_example_file:
        required: true
        type: string

      # Add more inputs as neede
      mongo_username:
        required: false
        type: string
      mongo_password:
        required: false
        type: string
      mongo_host:
        required: false
        type: string
      redis_password:
        required: false
        type: string
      redis_host:
        required: false
        type: string

jobs:
  unit-tests:
    name: Run Unit Tests - ${{ inputs.service_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.22"
      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            .moon/cache
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}

      - name: Prepare .env
        run: |
          ENV_EXAMPLE_FILE=${{ inputs.env_example_file || '.env.example' }}

          # Update .env.example keys
          if [ -n "${{ inputs.mongo_username }}" ]; then
            sed -i "s/^MONGO_INITDB_ROOT_USERNAME=.*/MONGO_INITDB_ROOT_USERNAME=${{ inputs.mongo_username }}/" "$ENV_EXAMPLE_FILE"
          fi
          if [ -n "${{ inputs.mongo_password }}" ]; then
            sed -i "s/^MONGO_INITDB_ROOT_PASSWORD=.*/MONGO_INITDB_ROOT_PASSWORD=${{ inputs.mongo_password }}/" "$ENV_EXAMPLE_FILE"
          fi
          if [ -n "${{ inputs.mongo_host }}" ]; then
            sed -i "s/^MONGO_HOST=.*/MONGO_HOST=${{ inputs.mongo_host }}/" "$ENV_EXAMPLE_FILE"
          fi
          if [ -n "${{ inputs.redis_password }}" ]; then
            sed -i "s/^REDIS_PASSWORD=.*/REDIS_PASSWORD=${{ inputs.redis_password }}/" "$ENV_EXAMPLE_FILE"
          fi
          if [ -n "${{ inputs.redis_host }}" ]; then
            sed -i "s/^REDIS_HOST=.*/REDIS_HOST=${{ inputs.redis_host }}/" "$ENV_EXAMPLE_FILE"
          fi

          cp "$ENV_EXAMPLE_FILE" "$(dirname "$ENV_EXAMPLE_FILE")/.env"

      - name: Run tests
        run: moon run ${{ inputs.service_name }}:test

  docker-build:
    name: Test Docker Build - ${{ inputs.service_name }}
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            .moon/cache
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
      - name: Build Docker image
        run: moon run ${{ inputs.service_name }}:docker-build
      - name: Show Docker images
        if: always()
        run: docker images | grep ${{ inputs.service_name }} || true
