replicaCount: 1

namespace: development

deployment:
  labels:
    environment: development

image:
  tag: "1.0"
  pullPolicy: Always

resources:
  requests:
    memory: "768Mi"
    cpu: "250m"
  limits:
    memory: "1.5Gi"
    cpu: "750m"

variables:
  secrets: development-secret
  config: development-config
