apiVersion: v2
name: etl-typechecking
description: RabbitMQ consumer for typechecking tasks
type: application
version: 1.0.0 # Version of the chart
appVersion: "1.0" # Version of the application

maintainers:
  - name: Juan Perez
  - name: Mauro Gonzalez
  - name: Diederik Monta√±o
