[project]
name = "ddl-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.10"
dependencies = [
    "asyncio>=3.4.3",
    "grpcio>=1.73.1",
    "grpcio-tools>=1.73.1",
    "pydantic-settings>=2.10.1",
]
