name: CD Production - Deploy to Production Environment
on:
  push:
    branches:
      - main
      - feat/CD # temporal
    paths:
      - iac/swarm/production/docker-stack.yml

jobs:
  deploy:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Setup basic files
        id: setup-files
        run: |
          SSH_KEY_PATH="iac/terraform/environments/production/ssh-keys/swarm-key.pem"
          SSH_KEY_FULL_PATH="$(pwd)/$SSH_KEY_PATH"
          echo "ssh-key-full-path=$SSH_KEY_FULL_PATH" >> $GITHUB_OUTPUT

          echo "${{ secrets.PRODUCTION_ENV_FILE }}" > iac/swarm/production/.env
          echo "${{ secrets.PRODUCTION_PRIVATE_SSH_KEY }}" > ${SSH_KEY_FULL_PATH}
          chmod 600 ${SSH_KEY_FULL_PATH}

      - name: Edit ssh config to use the key
        run: |
          SSH_KEY_FULL_PATH="${{ steps.setup-files.outputs.ssh-key-full-path }}"
          echo -e "Host ${{ secrets.PRODUCTION_SSH_HOST }}\n\tStrictHostKeyChecking no\n\tIdentityFile ${SSH_KEY_FULL_PATH}\n\tUserKnownHostsFile /dev/null\n" >> ~/.ssh/config
          chmod 644 ~/.ssh/config

      - name: Configure Docker Context
        run: |
          docker context create remote-production --docker "host=ssh://ubuntu@${{ secrets.PRODUCTION_SSH_HOST }}"
          docker context use remote-production

      - name: Deploy Docker Stack to Production
        run: moon run iac:swarm:deploy-production
