name: CI - API Tests
on:
  pull_request:
    branches:
      - main
      - staging
    paths:
      - "apps/backend/api/**"
      - "packages/messaging-utils/messaging-utils-py/**"
jobs:
  api-tests:
    # API uses PostgreSQL database, so...
    # TODO: configure postgres service
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/run-tests
        with:
          service_name: "api"
          env_example_file: "apps/backend/api/.env.example"
