name: CI - Excel Reader Tests
on:
  pull_request:
    branches:
      - main
      - staging
    paths:
      - "apps/backend/parsers/excel-reader/**"
      - "packages/proto-utils/proto-utils-py/**"

jobs:
  excel_reader-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/run-tests
        with:
          service_name: "excel-reader"
          env_example_file: "apps/backend/parsers/excel-reader/.env.example"
