name: CI - Formula Parser Tests
on:
  pull_request:
    branches:
      - main
      - staging
    paths:
      - "apps/backend/parsers/formula-parser/**"
      - "packages/proto-utils/proto-utils-py/**"

jobs:
  formula_parser-tests:
    uses: ./.github/workflows/reusable/ci-tests.yml
    with:
      service_name: "formula-parser"
      env_example_file: "apps/backend/parsers/formula-parser/.env.example"
