name: CI - SQL Builder Tests
on:
  pull_request:
    branches:
      - main
      - staging
    paths:
      - "apps/backend/parsers/sql-builder/**"
      - "packages/proto-utils/proto-utils-py/**"

jobs:
  sql_builder-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/run-tests
        with:
          service_name: "sql-builder"
          env_example_file: "apps/backend/parsers/sql-builder/.env.example"
