name: CI - Typechecking Tests
on:
  pull_request:
    branches:
      - main
      - staging
    paths:
      - "apps/backend/typechecking/**"
      - "packages/messaging-utils/messaging-utils-py/**"
      - "packages/proto-utils/proto-utils-py/**"

jobs:
  typechecking-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/run-tests
        with:
          service_name: "typechecking"
          env_example_file: "apps/backend/typechecking/.env.example"
