name: CI - Typechecking Tests
on:
  pull_request:
    branches:
      - main
      - staging
    paths:
      - apps/backend/typechecking/**
      - packages/messaging-utils/messaging-utils-py/**
      - packages/proto-utils/proto-utils-py/**
      - .github/actions/run-unit-tests/**
      - .github/workflows/ci-typechecking-tests.yml

jobs:
  typechecking-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/run-unit-tests
        with:
          service_name: "typechecking"
          env_example_file: "apps/backend/typechecking/.env.example"
      - name: Build Docker Image
        uses: ./.github/actions/build-docker-image
        with:
          service_name: "typechecking"
          verify_image: "true"
          push_image: "false"
