name: Reusable CI Tests

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      env_example_file:
        required: false
        type: string

jobs:
  unit-tests:
    name: Run Unit Tests - ${{ inputs.service_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.22"
      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            .moon/cache
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
      - name: Set up environment variables
        run: |
          envdir=$(dirname "${{ inputs.env_example_file }}")
          echo "Copying {{ inputs.env_example_file }} -> $envdir/.env"
          cp ${{ inputs.env_example_file }} "$envdir/.env"
      - name: Run tests
        run: moon run ${{ inputs.service_name }}:test

  docker-build:
    name: Test Docker Build - ${{ inputs.service_name }}
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            .moon/cache
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
      - name: Build Docker image
        run: moon run ${{ inputs.service_name }}:docker-build
      - name: Show Docker images
        if: always()
        run: docker images | grep ${{ inputs.service_name }} || true
